### PR TITLE
Switch order of params in executemany

### PR DESCRIPTION
**Pull request by Alex-Hall-Data**
Nothing special - just changed the order of the parameters in the ETL methods since wesaw they were inconsistent during the python clinic

### CODE REVIEW

**Comment by metazool** [comment]
Makes sense to me to risk back-incompatibility to obtain consistency at an early stage
Perhaps it makes sense to make them all keyword arguments at the interface to the function, they can still be used positionally
https://python-3-for-scientists.readthedocs.io/en/latest/python3_advanced.html

Relatedly I think in some cases we are seeing too many arguments - if you use pylint rather than flake8 it will complain at more than five. My rule of thumb is three before switching to keyword arguments to make things a bit clearer, especially when they have similar names, as in the inconsistency you found, Alex
https://github.com/PyCQA/pylint/blob/8a89edf3bf1aa00b93cc09507c8a32e71f9dc315/pylint/checkers/design_analysis.py

**Comment by dvalters** [comment]
Agreed - we're still in the 0.x.x of versioning so it's good to get it in now. We'll do this for now and consider changing to all keyword args in a later PR

**Comment by volcan01010** [comment]
@dvalters and I discussed this. We will make the change to `executemany` before we reach v1.0.  We have added a deprecation warning to advise users to use named arguments: #40.

We decided not to change the parameter order for `copy_rows` as we thought query, conn, query, conn was good for logically keeping the data source and destination components together.

We'll keep this merge request open until we have changed the parameter order.

**Comment by volcan01010** [comment]
Superseded by #58.

**Pull request closed without merging**
