### PR TITLE
Switch from cx_oracle to oracledb

### LINKED ISSUE #140: Replace cxOracle with python-oracledb
### Summary

As an ETL Helper user I want to use python-oracledb instead of cxOracle so that I don't need to worry about installing the Oracle Instant Client.

### Description

The [python-oracledb](https://oracle.github.io/python-oracledb/) driver is a replacement for cxOracle, which we currently use.  It has the big advantage that it doesn't require a separate installation of Oracle Instant Client to work.  Installing Instant Client is a pain - in fact part of the reason ETLHelper exists is to make this easier.

This should be as simple as updating the OracleDbHelper class to use the new driver and confirming that the tests still work.  If it does work, then we can remove the `setup_oracle_client` script as it will no longer be needed.  (Although we may want to keep it for in case the "thick" mode of the driver still needs it).

This change may have implications for #110 and #130 as it changes the underlying Oracle driver workings.  It is likely to be a breaking change.  Any changes should solve #110 so that `read_lob` is no longer required.

If it isn't a simple update then we should consider having two separate DbHelper classes for Oracle.  In the longer term, cxOracle will be deprecated to python-oracledb needs to work eventually.

### Acceptance criteria

+ [x] OracleDbHelper uses python-oracledb instead of cxOracle
+ [x] Documentation is updated explain that sections on `setup_oracle_client` and OS dependencies are only needed for "thick" mode
+ [x] `read_lob` parameter is deprecated

### PR DESCRIPTION
**Pull request by ximenesuk**
This pull request replaces `cx_Oracle` libraries with `oracledb` and bumps the minimum Python version to 3.9

The brute force approach of globally replacing  `cx_Oracle` with `oracledb` and adding `cffi` as a dependency resulted in all the tests passing. In addition the `setup.py` file has been updated to the new libraries. The `requirements.txt` file has also been updated. As an aside `all` has been added to setup uptions.

To test:
 - [x] `etlhelper` should `pip install` from this branch (with `all` option as additional test)
   - `pip install git+https://github.com/BritishGeologicalSurvey/etlhelper@oracledb#egg=etlhelper[all]`
   - `pip install git+https://github.com/BritishGeologicalSurvey/etlhelper@oracledb#egg=etlhelper[oracle]`
 - [x] all tests should pass
 - [x] the documentation should reflect the new libraries

Closes #140 and #160

### CODE REVIEW

**Comment by sophie-taylor** [comment]
I've tested this request on various scripts and all passed fine. Ready to commit

**Comment by leorudczenko** [comment]
I've just been going through other files to change for #158, and it seems there are still some mentions of the old `setup_oracle_client` in [CONTRIBUTING.md](https://github.com/BritishGeologicalSurvey/etlhelper/blob/oracledb/CONTRIBUTING.md) and potentially [bin/run_tests_for_developer.sh](https://github.com/BritishGeologicalSurvey/etlhelper/blob/oracledb/bin/run_tests_for_developer.sh) too.

Also, should this merge request be for `for_v1` rather than `main`?

**Comment by volcan01010** [comment]
OK, well spotted.  I'll change the target branch and update the docs.

**Comment by volcan01010** [comment]
This all works for me and I'm happy to merge into `for_v1`.

Note that https://github.com/BritishGeologicalSurvey/etlhelper/issues/110 discusses handling LOBs in a different way.  We should experiment with this now and decide what the default setting should be.

**Pull request merged**
