### PR TITLE
Ensure setup_oracle_client runs on sh and zsh

### LINKED ISSUE #80: ld_library_prepend.sh not compatible with sh
I saw this while installing etlhelper in a container with `sh` rather than `bash` as default shell (and using `.` rather than `source` to `$(setup_oracle_client)`

It doesn't like the `[[` syntax here https://github.com/BritishGeologicalSurvey/etlhelper/blob/e49ab8d2606f805142c21f5e8e9061d91f2c33f7/etlhelper/setup_oracle_client.py#L244  - "Double brackets are a bashism" https://scriptingosx.com/2018/02/single-brackets-vs-double-brackets/

I can switch my docker build to `bash` so it's not showstopping at all but i bet others will run into it

### PR DESCRIPTION
**Pull request by volcan01010**
### Description

This change in syntax in setup_oracle_client ensures that the `ld_libary_prepend.sh` script runs on `sh` shell.  A Dockerfile is added to confirm this, and that it works with `zsh`, too.  I looked into `csh` and `tcsh`, too, but they have completely different syntax.  We can consider supporting them if someone requests it, but we don't need it ourselves.

The Dockerfile is not used as part of routine testing.

Closes #80

### To test

+ [ ] Follow the instructions in `test/Dockerfile.test_shells` to check commands work

### CODE REVIEW

**Comment by volcan01010** [comment]
I'm in two minds about whether or not to include the Dockerfile.  If we never use it again it will just be clutter.  Thoughts appreciated.

**Comment by volcan01010** [comment]
I've decided to remove the Dockerfile.  If we need it back again, the code is in this commit: https://github.com/BritishGeologicalSurvey/etlhelper/pull/82/commits/ca4a6efaca16f7fe7d5f4fbcf71ab24b4a066364

**Comment by volcan01010** [comment]
I'll merge this; the full suite of tests pass so the build does work.

**Comment by metazool** [comment]
Thank you. I started looking at this but got caught up in other work waiting for the build, and never made the time to come back. It's good to see the fix  It's nice to have an example Dockerfile in the project, even though it wasn't being used in CI it was still a useful contribution

**Pull request merged**
