### PR TITLE
Make information on column types accessible

### LINKED ISSUE #127: Add describe_columns function
### Summary

As an ETLHelper user, I would like to get metadata on a table e.g. column names and types so that I can programmatically generate SQL queries.

### Description

Hard-coded SQL queries can be cumbersome in cases where tables have many columns.  `etlhelper` provides `load` to programmatically generate insert queries and `copy_table_rows` programmatically copies the rows from `SELECT * FROM table`, however they only cover the simple cases.

A `describe_columns(table, conn)` function would return metadata about a database table, with column names and types as a minimum.  These data can than be used to programmatically build a query.  For example, a geospatial insert query could wrap the geometry column in `ST_GeomFromText(%(geom)s, 4326)` to convert WKT into a geometry column.

### Implementation

The SQL query used to select the metadata is different for different database types.  As such, it will need to be defined on the DbHelper classes.  The queries will use the following internal tables / features:

+ PostgreSQL: [information_schema.columns](https://www.postgresql.org/docs/current/infoschema-columns.html)
+ SQLite: [PRAGMA table_info()](https://www.sqlite.org/pragma.html#pragma_table_info)
+ Oracle: TBC
+ MS SQL Server: TBC

The `describe_columns(table, conn)` function can live in a new module (`utils`).  It should execute the SQL query from the DbHelper and return a list of `Column` named tuples with attributes for at least "name" and "type" ~(and possibly "is_primary_key", "not_null", "default_value", which are provided in SQLite)~.

The function should also raise an exception if the table name in ambiguous e.g. if the same table appears in different schemas.  One way to detect this would be to detect non-unique column names.  This means that the function should accept simple and schema-qualified names.

### Acceptance criteria

Calling `describe_columns(table, conn)` against a table returns data for the following connection types:

+ [x] SQLite
+ [x] Oracle
+ [x] PostgreSQL
+ [x] MS SQL server

Bad column names raise exception:

+ [x] SQLite
+ [x] Oracle
+ [x] PostgreSQL
+ [x] MS SQL server

Schema qualified names can be used:

+ [x] Oracle
+ [x] PostgreSQL
+ [x] MS SQL server

Additional criteria

+ [x] `describe_columns` is available at top level `etlhelper` import
+ [ ] ~Subclass inheritance requires the query to be defined.~

### PR DESCRIPTION
**Pull request by volcan01010**
### Description

This merge request adds a `describe_columns` function that can return column metadata.

Closes #127

### To test

+ [x] Confirm that full test suite runs locally
+ [x] Confirm README updates make sense

### CODE REVIEW

**Comment by ximenesuk** [comment]
I have implemented this function for SQL Server. Due to the parameter handling there has been a little refactoring. The tests are passing locally.

**Comment by volcan01010** [comment]
Maybe SQLite does have a concept of schemas.  Or at least of two-part table names.

https://stackoverflow.com/questions/49660302/does-sqlite-have-the-concept-of-a-schema-in-naming-tables-views

Judging by this, we should set the schema to `main` if one isn't specified.

**Comment by ximenesuk** [comment]
> Maybe SQLite does have a concept of schemas. Or at least of two-part table names.
> 
> https://stackoverflow.com/questions/49660302/does-sqlite-have-the-concept-of-a-schema-in-naming-tables-views
> 
> Judging by this, we should set the schema to `main` if one isn't specified.

Yes, I was going to raise this as I saw "schemas" being used in an example. We need to work out how to use them dynamically as the format for schemas with pragmas is:
```
schema.pragma_name(...)
```

**Comment by volcan01010** [comment]
A tweak for the Oracle SQL query - we need to wrap the schema name in `^`, `$`, otherwise the REGEX is too greedy and matches BGS_BGSPROD when I searched for just BGS.

```sql
SELECT * FROM all_tab_columns
    WHERE LOWER(table_name) = LOWER('DIC_SEN_SENSOR')
    AND REGEXP_LIKE(LOWER(owner), COALESCE(LOWER('^' || 'BGS' || '$'), '.*'))
```

**Comment by ximenesuk** [comment]
Over to you @volcan01010

**Comment by volcan01010** [comment]
This is nearly ready to merge, but I can't get a connection to MS SQL Server to work for the integration tests.  Once we have that fixed and confirm that tests pass there, we can release.

**Comment by ximenesuk** [comment]
I've rerun the whole test suite including MS SQL Server and all tests pass.

**Pull request merged**
