### PR TITLE
Change instances of sql_server to mssql for consistency

### LINKED ISSUE #5: Consolidate MSSQL vs SQLServer
## Summary

In some locations in the code Microsoft SQL Server is referred to as `mssql`, in others it is `sql_server`.  One of these should be chosen and used consistently to avoid confusion.

## Acceptance criteria

+ [ ] `sql_server` or `mssql` are used consistently throughout the code.

### PR DESCRIPTION
**Pull request by dvalters**
Closes #5 

with:

```
git grep -l 'sql_server' | xargs sed -i 's/sql_server/mssql/g'
```

### CODE REVIEW

**Comment by volcan01010** [comment]
I like your confidence in the sed solution!  There may be filenames that need changing, too.

**Comment by dvalters** [comment]
Oh yes, good point there are some filenames too.

**Comment by dvalters** [comment]
I renamed the files by hand. There is a way to do the files programmatically with `git ls-files`, `xargs`, and  `rename`, but I'll leave it as an exercise for future readers...

**Comment by volcan01010** [comment]
Can you rename the DbHelper, too?

`MssqlDbHelper`? `MsSqlDbHelper`? `MSSQLDbHelper`? I think I prefer the last one.

https://github.com/BritishGeologicalSurvey/etlhelper/blob/ef0c2646a8a218cc061d6cb614e7e0380b2bb54b/etlhelper/db_helpers/mssql.py#L7

**Comment by volcan01010** [comment]
Looks good.  I haven't run locally but will trust the tests in CI.

**Pull request merged**
