### PR TITLE
Add build & push to GH Container Registry

### PR DESCRIPTION
**Pull request by KoalaGeo**
Add build & push to GH Container Registry, README also updated

### CODE REVIEW

**Comment by volcan01010** [comment]
Hi Edd, this would be good to do.  I did think about it before, and can't remember why I didn't do it.  Probably because I didn't have time to work out the GitHub action and we already had a working version internally.

We need to check some licences before we can distribute this.  The Docker container includes drivers for Microsoft SQL Server (MS ODBC) and the Oracle Instant Client.  You have to explicitly accept a EULA to install MSODBC.  Oracle Instant Client used to be behind a password-protected download but it is more open now and I think you are allowed to redistribute.  It may be that we just need to add some Copyright / Licence notices in appropriate places.

I noticed in the build file that the tag on the container is `etlhelper`.  We'd need to append `:latest` or a version number to that so that users can control the version that they download.

**Comment by KoalaGeo** [comment]
Ah - yeah that sound's like it does need some sort of notice on it....

https://github.com/KoalaGeo/etlhelper/blob/82a7be45a1050ed5d28fa14b4872dfa045cfc47c/.github/workflows/main.yml#L48 add's the release version as a tag

https://github.com/KoalaGeo/etlhelper/blob/82a7be45a1050ed5d28fa14b4872dfa045cfc47c/.github/workflows/main.yml#L50 uses latest if not from a tagged release

**Comment by volcan01010** [comment]
Ah yes, now I remember writing those lines with the tags together for AGS validator!

**Comment by volcan01010** [comment]
I knew that I had started looking at that!  I found the branch:

https://github.com/BritishGeologicalSurvey/etlhelper/compare/docker-in-github

My aim was to build it with a tagged version whenever we made a new release.

This Dockerfile is stripped back so that it doesn't contain any of the testing or development dependencies.  It only has PostgreSQL and Oracle drivers.  I think it's OK if we just say on the website that you have to build your own to use MS SQL Server and point users at the main Dockerfile.

Here is the license for the Oracle Instant Client.  Can you please check what we would need to do to include it: https://www.oracle.com/downloads/licenses/distribution-license.html

**Pull request closed without merging**
